---
title: Multi-branch versioning with Jekyll made easy
description: Why and how to setup multi-branch versioning with Jekyll

baseurl: /JekyllVersioningWorkflows
url: http://djacquel.github.io/JekyllVersioningWorkflows
twitter_username: djacquel
github_username: djacquel
markdown: kramdown
destination: _site

exclude: [ Rakefile ]
